name: crane_plugin
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  share: ^2.0.4
#  url_launcher: ^6.1.6
#  toast: ^0.1.5
  fluttertoast: ^8.0.9

  path_provider: ^2.0.11

  shared_preferences: ^2.0.15

  http: ^0.13.4
  flutter_spinkit: ^5.1.0

#  umeng_common_sdk: ^1.2.4
  event_bus: ^2.0.0
  intl: ^0.17.0
  provider: ^6.0.3
  cached_network_image: ^3.2.1

  bot_toast: ^4.0.3
  fl_umeng: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: cn.crane.crane_plugin
        pluginClass: CranePlugin
      ios:
        pluginClass: CranePlugin
      macos:
        pluginClass: CranePlugin
      web:
        pluginClass: CranePluginWeb
        fileName: crane_plugin_web.dart

  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/tos/

flutter_intl:
  enabled: true